name: Full Thẩm Định Pipeline

on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install system dependencies (for Playwright Chromium)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 libxshmfence1 libnss3 libatk1.0-0 libcups2 \
            libxcomposite1 libxrandr2 libxdamage1 libgbm1 libxkbcommon0 \
            libgtk-3-0 libxss1 libgdk-pixbuf2.0-0 libx11-xcb1

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps

      - name: Run download PDF
        run: python download_pdf.py

      - name: Run OCR to JSON
        run: python ocr_to_json.py

      - name: Extract to Google Sheet
        run: python extract_to_sheet.py
