name: Full PDF OCR Pipeline

on:
  workflow_dispatch:  # Cho phép bạn chạy thủ công từ GitHub Actions UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run download PDF
        run: |
          python download_pdf.py

      - name: OCR to JSON (Document AI)
        run: |
          python ocr_to_json.py

      - name: Extract to Google Sheet
        run: |
          python extract_to_sheet.py
